### ISSUE TITLE
Can not run

### ISSUE THREAD

**Issue by jinleileiking** [Eyevinn/webrtc-player#39]
```

❯ npm -v
8.19.2


❯ node -v
v19.0.0


❯ uname -a
Linux debian 5.10.0-18-amd64 #1 SMP Debian 5.10.140-1 (2022-09-02) x86_64 GNU/Linux


```

```
❯ npm run dev

> @eyevinn/webrtc-player@0.10.0 dev
> parcel --target demo --dist-dir dist-demo --host 0.0.0.0 --port 2345 --no-cache

Error: No native build was found for platform=linux arch=x64 runtime=node abi=111 uv=1 libc=glibc node=19.0.0
    loaded from: /home/jinlei/oss/webrtc-player/node_modules/lmdb

    at load.path (/home/jinlei/oss/webrtc-player/node_modules/node-gyp-build/index.js:60:9)
    at load (/home/jinlei/oss/webrtc-player/node_modules/node-gyp-build/index.js:22:30)
    at Object.<anonymous> (/home/jinlei/oss/webrtc-player/node_modules/lmdb/dist/index.cjs:2257:47)
    at Module._compile (/home/jinlei/oss/webrtc-player/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (/home/jinlei/oss/webrtc-player/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at _lmdb (/home/jinlei/oss/webrtc-player/node_modules/@parcel/cache/lib/LMDBCache.js:51:39)

```

**Comment by birme** [comment]
This should be solved now
